#name: cropmask
channels:
  - conda-forge
dependencies:
  # Core scientific python
  - numpy
  - matplotlib
  - python=3.6
  - pyqt
  - seaborn
  - xlrd # for excel sheets in pandas
  - scipy
  - scikit-learn

# Mask_RCNN requirements
  - Pillow
  - cython
  - matplotlib
  - scikit-image
  - tensorflow>=1.3.0
  - keras>=2.0.8
  - opencv
  - h5py
  - IPython[all]


  # Extensions
  - autopep8

  # Geo stuff
  - rasterstats
  - geopy
  - cartopy
  - geopandas
  - rasterio
  - contextily
  - pysal
  - pyproj
  - folium
  - scikit-image
  - gdal
  - libgdal
  - kealib
  - geocoder
  - geojson

  # Natural language processing
  - tweepy
  - nltk
  - textblob

  - pip:
      # Utilities
      - download
      - tqdm
      - kiwisolver
      # EA tools via pip
      - mapboxgl
      - hydrofunctions
      - lsru
      - porder
      - imgaug # for MaskRCNN
